version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  web:
    build: .docker-compose downpython -m pip install --upgrade
    container_name: django_app
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://myuser:mypassword@db:3306/mydb
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  mysql_data:
